# Generated by Django 4.1.6 on 2023-05-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassePrimaire',
            fields=[
                ('idClassePrimaire', models.AutoField(primary_key=True, serialize=False)),
                ('classePName', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClasseSecondaire',
            fields=[
                ('idClasseSecondaire', models.AutoField(primary_key=True, serialize=False)),
                ('classeSName', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('idDelegation', models.AutoField(primary_key=True, serialize=False)),
                ('nomDelegation', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenerateID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idPatient', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mutuelle',
            fields=[
                ('idMutuelle', models.AutoField(primary_key=True, serialize=False)),
                ('mutuelleName', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObesiteImc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.IntegerField(default=0)),
                ('obesite_date', models.DateField(null=True)),
                ('obesite_poids', models.CharField(blank=True, default='1', max_length=300, null=True)),
                ('obesite_taille', models.CharField(blank=True, default='1', max_length=300, null=True)),
                ('imc', models.CharField(blank=True, default='1', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathologieCardiqueOpere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.IntegerField(default=0)),
                ('opere_date', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('opere_type', models.CharField(blank=True, default='1', max_length=300, null=True)),
                ('opere_suivi', models.CharField(blank=True, default='Non', max_length=3, null=True)),
                ('opere_suivi_date', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathologieDentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.IntegerField(default=0)),
                ('date_act', models.CharField(default='01/01/2022', max_length=100, null=True)),
                ('dent_GaucheDroit', models.CharField(blank=True, default='G', max_length=50, null=True)),
                ('dent_HautBas', models.CharField(blank=True, default='H', max_length=50, null=True)),
                ('dent_num', models.CharField(blank=True, default='1', max_length=50, null=True)),
                ('code_act', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
