# Generated by Django 4.1.6 on 2023-05-29 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('actualite_id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=120)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('texte', models.TextField()),
                ('auteur', models.CharField(max_length=40)),
                ('pdf', models.FileField(null=True, upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
