# Generated by Django 4.1.6 on 2023-05-29 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pediatre', '0001_initial'),
        ('Administrateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nomAdmin', models.CharField(max_length=60)),
                ('prenomAdmin', models.CharField(max_length=60)),
                ('passwordAdmin', models.CharField(max_length=60)),
                ('mailAdmin', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('idConversation', models.AutoField(primary_key=True, serialize=False)),
                ('sujet', models.CharField(default='No Subject', max_length=300)),
                ('dateStart', models.CharField(default='2023-05-30 00:50:06', max_length=100)),
                ('dateUpdated', models.CharField(default='2023-05-30 00:50:06', max_length=100)),
                ('nbrMessage', models.IntegerField(default=1)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_conversation', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_conversation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='imgGalerie/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('lien', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idMessage', models.AutoField(primary_key=True, serialize=False)),
                ('dateEnvoie', models.CharField(default='2023-05-30 00:50:06', max_length=100)),
                ('vu', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrateur.conversation')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
